In [1]:
import pandas as pd
import numpy as np
import sklearn.metrics as metrics
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
##Cardio dataset, anomalies 비율 수정하여 file화 cardio -> cardioForAnomailes
cardio = pd.read_csv('Dataset/cardioForAnomalies.csv')
cardio_X = cardio.iloc[:,:12]
cardio_y = cardio['cardio']

In [3]:
## kddcup99
kddcup = pd.read_csv('Dataset/kddcup99.csv')
kddcup_X = kddcup.iloc[:,:-1]
kddcup_y =kddcup.iloc[:,-1]

kddcup_cat_clos = ['protocol_type', 'service', 'flag']
kddcup_X = pd.get_dummies(kddcup_X, columns = kddcup_cat_clos)
f = lambda x : -1 if x =='normal' else 1
kddcup_y = kddcup_y.map(f)

In [4]:
##kddcup_rev, anomailes 비율조정 및 file화 kddcup99 -> kddcup_rev
kddcup_rev = pd.read_csv('Dataset/kddcup_rev.csv', index_col=0)
kddcup_rev_X = kddcup_rev.iloc[:,:-1]
kddcup_rev_y = kddcup_rev.iloc[:,-1]

kddcup_rev_X = pd.get_dummies(kddcup_rev_X, columns = kddcup_cat_clos)
f = lambda x : 1 if x =='normal' else -1
kddcup_rev_y = kddcup_rev_y.map(f)

In [5]:
##defaultCredit
defaultCredit = pd.read_csv('Dataset/defaultCreditCard.csv', header = 0)

In [6]:
##dryBean
dryBean = pd.read_csv('Dataset/DryBean.csv', header = 0)

In [7]:
##mnist
mnist = pd.read_csv('Dataset/mnist.csv')

In [8]:
##fashion-mnist
fashion_mnist = pd.read_csv('Dataset/fashion_mnist.csv')

In [9]:
##cifiar10

def unpickle(file):
    import pickle
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

c10_path = 'Dataset/cifar10/'

c10_train1_dict = unpickle(c10_path+'data_batch_1')
c10_train2_dict = unpickle(c10_path+'data_batch_2')
c10_train3_dict = unpickle(c10_path+'data_batch_3')
c10_train4_dict = unpickle(c10_path+'data_batch_4')
c10_train5_dict = unpickle(c10_path+'data_batch_5')
c10_test_dict = unpickle(c10_path+'test_batch')

c10_train1 = pd.DataFrame(c10_train1_dict[b'data'])
c10_y1 = pd.DataFrame(c10_train1_dict[b'labels'])

c10_train2 = pd.DataFrame(c10_train2_dict[b'data'])
c10_y2 = pd.DataFrame(c10_train2_dict[b'labels'])

c10_train3 = pd.DataFrame(c10_train3_dict[b'data'])
c10_y3 = pd.DataFrame(c10_train3_dict[b'labels'])

c10_train4 = pd.DataFrame(c10_train4_dict[b'data'])
c10_y4 = pd.DataFrame(c10_train4_dict[b'labels'])

c10_train5 = pd.DataFrame(c10_train5_dict[b'data'])
c10_y5 = pd.DataFrame(c10_train5_dict[b'labels'])


c10_test = pd.DataFrame(c10_test_dict[b'data'])
c10_test_y = pd.DataFrame(c10_test_dict[b'labels'])


c10_X = pd.concat([c10_train1, c10_train2, c10_train3, c10_train4, c10_train5, c10_test])
c10_y = pd.concat([c10_y1, c10_y2, c10_y3, c10_y4, c10_y5, c10_test_y])

In [10]:
#cifar100
c100_path = 'Dataset/cifar100/' # change this path
# File paths
c100_train_path = c100_path + 'train'
c100_test_path = c100_path + 'test'
# Read dictionary
c100_train_dict = unpickle(c100_train_path)
c100_test_dict = unpickle(c100_test_path)
# Get data (change the coarse_labels if you want to use the 100 classes)
c100_train = pd.DataFrame(c100_train_dict[b'data'])
c100_label_train = pd.DataFrame(np.array(c100_train_dict[b'coarse_labels']))
c100_test = pd.DataFrame(c100_test_dict[b'data'])
c100_label_test = pd.DataFrame(np.array(c100_test_dict[b'coarse_labels']))


c100_X = pd.concat([c100_train, c100_test])
c100_y = pd.concat([c100_label_train, c100_label_test])

In [11]:
c100_X

,0,1,2,3,4,5,6,7,8,9,...,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071
0,255,255,255,255,255,255,255,255,255,255,...,43,74,76,47,47,24,4,10,59,79
1,255,253,253,253,253,253,253,253,253,253,...,253,253,253,253,253,253,253,253,253,255
2,250,248,247,248,249,249,248,248,247,247,...,197,196,193,191,190,189,190,194,207,228
3,124,131,135,138,140,144,148,152,156,158,...,198,206,215,216,217,221,223,232,236,231
4,43,32,87,127,55,48,51,87,121,113,...,38,63,70,54,76,50,78,60,29,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,158,118,78,65,101,174,134,102,100,132,...,219,218,164,125,111,82,57,37,11,2
9996,100,113,130,132,127,129,138,139,133,125,...,97,82,47,43,56,89,105,96,83,81
9997,24,24,22,13,17,18,14,15,16,25,...,19,30,31,31,58,43,14,20,54,54
9998,86,93,28,43,94,95,76,84,52,36,...,110,120,124,124,123,123,124,119,115,109
9999,246,240,214,161,94,75,60,53,94,100,...,16,78,140,53,72,54,55,114,141,118

In [32]:
def train_val_test_split(X, y, splitCount, unlabelSize, test_val_size, random_seed):    
    
    split = StratifiedShuffleSplit(n_splits=1, test_size=unlabelSize, random_state = random_seed)
    
    train =[]
    unlabel =[]
    label=[]
    test_val=[]
    test =[]
    val =[]
    
    for label_id, unlabel_id in split.split(X,y):
        
        label.append(label_id)        
        unlabel.append(unlabel_id)
        
        label_X = X.iloc[label[0]]
        label_y = y.iloc[label[0]]
                
        unlabel_X = X.iloc[unlabel[0]]
        unlabel_y = y.iloc[unlabel[0]]
        
        split2 = StratifiedShuffleSplit(n_splits=1, test_size=test_val_size, random_state =random_seed)
        
        for train_id, test_val_id in split2.split(label_X, label_y):
            
            train.append(train_id)
            test_val.append(test_val_id)
            
            test_val_X = label_X.iloc[test_val[0]]
            test_val_y = label_y.iloc[test_val[0]]
            
            train_X = label_X.iloc[train[0]]
            train_y = label_y.iloc[train[0]]            
            
            
            split3 = StratifiedShuffleSplit(n_splits=1, test_size=0.5, random_state=random_seed)
            
            for val_id, test_id in split3.split(test_val_X, test_val_y):
                               
                val.append(val_id)
                test.append(test_id)
                
                val_X = test_val_X.iloc[val[0]]
                val_y = test_val_y.iloc[val[0]]
                
                test_X = test_val_X.iloc[test[0]]
                test_y = test_val_y.iloc[test[0]]
        
        
    return  train_X, train_y, unlabel_X, unlabel_y, val_X, val_y, test_X, test_y

In [34]:
def getTrain(k, X, y):
    if k >10:
        return print("k must be 1~10")
    data = train_val_test_split(X, y, splitCount=10, unlabelSize=0.7, test_val_size=0.3, random_seed=k+72)
    train_X = data[0].reset_index(drop=True)
    train_y = data[1].reset_index(drop=True)
    print(train_y.value_counts())
    return train_X, train_y

In [35]:
def getUnlabel(k, X, y):
    if k >10:
        return print("k must be 1~10")
    data = train_val_test_split(X, y, splitCount=10, unlabelSize=0.7, test_val_size=0.3, random_seed=k+72)
    unlabel_X = data[2].reset_index(drop=True)
    unlabel_y = data[3].reset_index(drop=True)
    print(unlabel_y.value_counts())
    return unlabel_X, unlabel_y

In [36]:
def getVal(k, X, y):
    if k >10:
        return print("k must be 1~10")
    data = train_val_test_split(X, y, splitCount=10, unlabelSize=0.7, test_val_size=0.3, random_seed=k+72)
    val_X = data[4].reset_index(drop=True)
    val_y = data[5].reset_index(drop=True)
    print(val_y.value_counts())
    return val_X, val_y

In [17]:
def getTest(k, X, y):
    if k >10:
        return print("k must be 1~10")
    data = train_val_test_split(X, y, splitCount=10, unlabelSize=0.7, test_val_size=0.3, random_seed=k+72)
    test_X = data[6].reset_index(drop=True)
    test_y = data[7].reset_index(drop=True)
    print(test_y.value_counts())
    return test_X, test_y

In [37]:
trainX, trainy = getTrain(1, kddcup_X, kddcup_y)

 1    83316
-1    20428
Name: label, dtype: int64

In [19]:
trainX

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,320,525,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103741,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
103742,0,218,341,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
103743,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [20]:
trainy

0         1
1         1
2         1
3        -1
4         1
         ..
103739    1
103740    1
103741   -1
103742   -1
103743    1
Name: label, Length: 103744, dtype: int64

In [28]:
from collections import Counter
Counter(trainy)

Counter({1: 54726, -1: 49018})

In [29]:
valX, valy = getVal(1, kddcup_X, kddcup_y)

In [31]:
Counter(valy)

Counter({-1: 19018, 1: 3213})

In [21]:
trainX, trainy = getTrain(1, kddcup_X, kddcup_y)

In [22]:
trainX

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,320,525,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103741,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
103742,0,218,341,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
103743,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [23]:
trainy

0         1
1         1
2         1
3        -1
4         1
         ..
103739    1
103740    1
103741   -1
103742   -1
103743    1
Name: label, Length: 103744, dtype: int64

In [24]:
trainX, trainy = getTrain(2, kddcup_X, kddcup_y)

In [25]:
testX, testy = getTest(3, kddcup_X, kddcup_y)

In [26]:
trainX

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,1032,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,277,330,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103739,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103740,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
103741,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
103742,0,216,415,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
103743,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [27]:
testX

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,lnum_compromised,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,250,25858,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
1,0,279,758,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
2,0,257,365,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,0,345,515,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,0,230,2527,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22226,0,1342,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
22227,0,207,604,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
22228,0,297,835,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
22229,0,229,661,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
22230,0,206,1060,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0